// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: rpc_get_payment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPaymentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentStatusRequest) Reset() {
	*x = GetPaymentStatusRequest{}
	mi := &file_rpc_get_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentStatusRequest) ProtoMessage() {}

func (x *GetPaymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_payment_proto_rawDescGZIP(), []int{0}
}

func (x *GetPaymentStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPaymentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentStatusResponse) Reset() {
	*x = GetPaymentStatusResponse{}
	mi := &file_rpc_get_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentStatusResponse) ProtoMessage() {}

func (x *GetPaymentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentStatusResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentStatusResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_payment_proto_rawDescGZIP(), []int{1}
}

func (x *GetPaymentStatusResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

var File_rpc_get_payment_proto protoreflect.FileDescriptor

const file_rpc_get_payment_proto_rawDesc = "" +
	"\n" +
	"\x15rpc_get_payment.proto\x12\x02pb\x1a\rpayment.proto\")\n" +
	"\x17GetPaymentStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"A\n" +
	"\x18GetPaymentStatusResponse\x12%\n" +
	"\apayment\x18\x01 \x01(\v2\v.pb.PaymentR\apaymentBDZBgithub.com/joekingsleyMukundi/backend-intern-assesment/payments/pbb\x06proto3"

var (
	file_rpc_get_payment_proto_rawDescOnce sync.Once
	file_rpc_get_payment_proto_rawDescData []byte
)

func file_rpc_get_payment_proto_rawDescGZIP() []byte {
	file_rpc_get_payment_proto_rawDescOnce.Do(func() {
		file_rpc_get_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_get_payment_proto_rawDesc), len(file_rpc_get_payment_proto_rawDesc)))
	})
	return file_rpc_get_payment_proto_rawDescData
}

var file_rpc_get_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_payment_proto_goTypes = []any{
	(*GetPaymentStatusRequest)(nil),  // 0: pb.GetPaymentStatusRequest
	(*GetPaymentStatusResponse)(nil), // 1: pb.GetPaymentStatusResponse
	(*Payment)(nil),                  // 2: pb.Payment
}
var file_rpc_get_payment_proto_depIdxs = []int32{
	2, // 0: pb.GetPaymentStatusResponse.payment:type_name -> pb.Payment
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_get_payment_proto_init() }
func file_rpc_get_payment_proto_init() {
	if File_rpc_get_payment_proto != nil {
		return
	}
	file_payment_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_get_payment_proto_rawDesc), len(file_rpc_get_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_payment_proto_goTypes,
		DependencyIndexes: file_rpc_get_payment_proto_depIdxs,
		MessageInfos:      file_rpc_get_payment_proto_msgTypes,
	}.Build()
	File_rpc_get_payment_proto = out.File
	file_rpc_get_payment_proto_goTypes = nil
	file_rpc_get_payment_proto_depIdxs = nil
}
