// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: rpc_initialize_payment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitializePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializePaymentRequest) Reset() {
	*x = InitializePaymentRequest{}
	mi := &file_rpc_initialize_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializePaymentRequest) ProtoMessage() {}

func (x *InitializePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_initialize_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializePaymentRequest.ProtoReflect.Descriptor instead.
func (*InitializePaymentRequest) Descriptor() ([]byte, []int) {
	return file_rpc_initialize_payment_proto_rawDescGZIP(), []int{0}
}

func (x *InitializePaymentRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *InitializePaymentRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type InitializePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializePaymentResponse) Reset() {
	*x = InitializePaymentResponse{}
	mi := &file_rpc_initialize_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializePaymentResponse) ProtoMessage() {}

func (x *InitializePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_initialize_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializePaymentResponse.ProtoReflect.Descriptor instead.
func (*InitializePaymentResponse) Descriptor() ([]byte, []int) {
	return file_rpc_initialize_payment_proto_rawDescGZIP(), []int{1}
}

func (x *InitializePaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

var File_rpc_initialize_payment_proto protoreflect.FileDescriptor

const file_rpc_initialize_payment_proto_rawDesc = "" +
	"\n" +
	"\x1crpc_initialize_payment.proto\x12\x02pb\x1a\rpayment.proto\"H\n" +
	"\x18InitializePaymentRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\"B\n" +
	"\x19InitializePaymentResponse\x12%\n" +
	"\apayment\x18\x01 \x01(\v2\v.pb.PaymentR\apaymentBDZBgithub.com/joekingsleyMukundi/backend-intern-assesment/payments/pbb\x06proto3"

var (
	file_rpc_initialize_payment_proto_rawDescOnce sync.Once
	file_rpc_initialize_payment_proto_rawDescData []byte
)

func file_rpc_initialize_payment_proto_rawDescGZIP() []byte {
	file_rpc_initialize_payment_proto_rawDescOnce.Do(func() {
		file_rpc_initialize_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_initialize_payment_proto_rawDesc), len(file_rpc_initialize_payment_proto_rawDesc)))
	})
	return file_rpc_initialize_payment_proto_rawDescData
}

var file_rpc_initialize_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_initialize_payment_proto_goTypes = []any{
	(*InitializePaymentRequest)(nil),  // 0: pb.InitializePaymentRequest
	(*InitializePaymentResponse)(nil), // 1: pb.InitializePaymentResponse
	(*Payment)(nil),                   // 2: pb.Payment
}
var file_rpc_initialize_payment_proto_depIdxs = []int32{
	2, // 0: pb.InitializePaymentResponse.payment:type_name -> pb.Payment
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_initialize_payment_proto_init() }
func file_rpc_initialize_payment_proto_init() {
	if File_rpc_initialize_payment_proto != nil {
		return
	}
	file_payment_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_initialize_payment_proto_rawDesc), len(file_rpc_initialize_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_initialize_payment_proto_goTypes,
		DependencyIndexes: file_rpc_initialize_payment_proto_depIdxs,
		MessageInfos:      file_rpc_initialize_payment_proto_msgTypes,
	}.Build()
	File_rpc_initialize_payment_proto = out.File
	file_rpc_initialize_payment_proto_goTypes = nil
	file_rpc_initialize_payment_proto_depIdxs = nil
}
