// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: service_payment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_payment_proto protoreflect.FileDescriptor

const file_service_payment_proto_rawDesc = "" +
	"\n" +
	"\x15service_payment.proto\x12\x02pb\x1a\x1crpc_initialize_payment.proto\x1a\x18rpc_update_payment.proto2\xa2\x01\n" +
	"\x04Auth\x12R\n" +
	"\x11InitializePayment\x12\x1c.pb.InitializePaymentRequest\x1a\x1d.pb.InitializePaymentResponse\"\x00\x12F\n" +
	"\rUpdatePayment\x12\x18.pb.UpdatePaymentRequest\x1a\x19.pb.UpdatePaymentResponse\"\x00BDZBgithub.com/joekingsleyMukundi/backend-intern-assesment/payments/pbb\x06proto3"

var file_service_payment_proto_goTypes = []any{
	(*InitializePaymentRequest)(nil),  // 0: pb.InitializePaymentRequest
	(*UpdatePaymentRequest)(nil),      // 1: pb.UpdatePaymentRequest
	(*InitializePaymentResponse)(nil), // 2: pb.InitializePaymentResponse
	(*UpdatePaymentResponse)(nil),     // 3: pb.UpdatePaymentResponse
}
var file_service_payment_proto_depIdxs = []int32{
	0, // 0: pb.Auth.InitializePayment:input_type -> pb.InitializePaymentRequest
	1, // 1: pb.Auth.UpdatePayment:input_type -> pb.UpdatePaymentRequest
	2, // 2: pb.Auth.InitializePayment:output_type -> pb.InitializePaymentResponse
	3, // 3: pb.Auth.UpdatePayment:output_type -> pb.UpdatePaymentResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_payment_proto_init() }
func file_service_payment_proto_init() {
	if File_service_payment_proto != nil {
		return
	}
	file_rpc_initialize_payment_proto_init()
	file_rpc_update_payment_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_payment_proto_rawDesc), len(file_service_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_payment_proto_goTypes,
		DependencyIndexes: file_service_payment_proto_depIdxs,
	}.Build()
	File_service_payment_proto = out.File
	file_service_payment_proto_goTypes = nil
	file_service_payment_proto_depIdxs = nil
}
