// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: payment.sql

package db

import (
	"context"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    owner, amount, status
) VALUES (
    $1, $2, $3
)
RETURNING id, owner, amount, status, created_at
`

type CreatePaymentParams struct {
	Owner  string `json:"owner"`
	Amount int64  `json:"amount"`
	Status string `json:"status"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment, arg.Owner, arg.Amount, arg.Status)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, owner, amount, status, created_at FROM payments
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPayment(ctx context.Context, id int64) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listPayments = `-- name: ListPayments :many
SELECT id, owner, amount, status, created_at FROM payments
ORDER BY id
LIMIT $1
OFFSET $1
`

func (q *Queries) ListPayments(ctx context.Context, offset int32) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listPayments, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePayment = `-- name: UpdatePayment :one
UPDATE payments
    set status = $2
WHERE id = $1
RETURNING id, owner, amount, status, created_at
`

type UpdatePaymentParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, updatePayment, arg.ID, arg.Status)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
