// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetPayment(ctx context.Context, id int64) (Payment, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListPayments(ctx context.Context, offset int32) ([]Payment, error)
	UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (Payment, error)
}

var _ Querier = (*Queries)(nil)
