syntax = "proto3";

package pb;

import "rpc_initialize_payment.proto";
import "rpc_update_payment.proto";
import "rpc_get_payment.proto";

option go_package = "github.com/joekingsleyMukundi/backend-intern-assesment/payments/pb"; 

service Payments{
    rpc InitializePayment (InitializePaymentRequest) returns (InitializePaymentResponse){};
    rpc UpdatePayment (UpdatePaymentRequest) returns (UpdatePaymentResponse) {}
    rpc GetPaymentstatus (GetPaymentStatusRequest) returns (GetPaymentStatusResponse) {}
}